spring:
  application:
    swagger:
      title: '@name@'
      description: '@description@'
      version: '@version@'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:validator
    username: dantas
    password: 123456
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true