spring:
  application:
    swagger:
      title: "APP-VALIDATION-PASSWORD-JAVA"
      description: "APPLICATION FOR VALIDATION PASSWORD"
      version: "1.0.0"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:mydb
    username: dantas
    password: 123456
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true